from cerr import plan_container as pc

if __name__ == "__main__":

    # Path to a DICOM dataset for an image
    dcm_dir = r"\\path\to\DICOM\Pt1"

    import time
    t = time.time()
    planC = pc.load_dcm_dir(dcm_dir)
    elapsed = time.time() - t
    print(f"Time spent to read dicom into planC = {elapsed/60:.2f} minutes")


    # Show scan, structure and dose overlay
    from cerr import viewer as vwr
    import numpy as np
    num_structs = len(planC.structure)
    str_num_list = np.arange(num_structs)
    scan_num = [0]
    dose_num = [0]  # 0
    str_num_list = [17] #np.arange(num_structs)  # [0]
    viewer, scan_layer, dose_layer, labels_layer = vwr.show_scan_struct_dose(scan_num, str_num_list, dose_num, planC)


    # Immport image using simpleitk
    scan_dir = r"\\path\to\DICOM\Pt1\scan_subdir"
    import SimpleITK as sitk
    reader = sitk.ImageSeriesReader()
    dicom_names = reader.GetGDCMSeriesFileNames(scan_dir)
    reader.SetFileNames(dicom_names)
    image = reader.Execute()
    npSitkImg = sitk.GetArrayFromImage(image)
    print("npSitkImg shape {0}".format(npSitkImg.shape))

    import numpy as np
    image_fromPyCERR = planC.scan[0].getSitkImage()
    npSitkCerrImg = sitk.GetArrayFromImage(image_fromPyCERR)
    diff3M = np.abs((npSitkCerrImg - npSitkImg) / (npSitkImg + np.finfo(float).eps) * 100)
    diff3M.mean()


    # Import segmentation from nii
    niiStructFileName = r'\\vpensmph\deasylab2\Aditya\Radiomics_features\nii_import_test\GTV_0617-381906_09-09-2000-87022.nii.gz'
    assocScanNum = 0
    labelsDict = {1: "test"}
    planC = pc.load_nii_structure(niiStructFileName, assocScanNum, planC, labelsDict)

    # Export RTSTRUCT to DICOM
    from cerr.dcm_export import rtstruct_iod
    rtstruct_file = r"\\vpensmph\deasylab2\Aditya\Radiomics_features\test_rtstruct_2.dcm"
    seriesDescription = 'Generated by AI model'
    structNumV = [5,6]
    structNumV = [13]
    rtstruct_iod.create(structNumV,rtstruct_file,planC,seriesDescription)

    # Export scan, structure to nii
    import os
    scanNum = 0
    scanNiiName = r'\\path\to\save\nii\scan.nii.gz'
    planC.scan[scanNum].save_nii(scanNiiName)

    str_num = 5
    str_name = planC.structure[str_num].structureName
    strNiiName = os.path.join(r'\\path\to\save\nii\structure',str_name+'.nii.gz')
    planC.structure[str_num].save_nii(strNiiName,planC)

    dose_num = 0
    dose_name = 'rtdose'
    doseNiiName = os.path.join(r'path\to\save\nii\dose',dose_name+'.nii.gz')
    planC.dose[dose_num].save_nii(doseNiiName)




