# Module to export deformable image registration (DVF) to a REG DICOM file
# (Deformable Spatial Registration IOD, SOPClassUID 1.2.840.10008.5.1.4.1.1.66.3).
#
# Integrated from the standalone reg2dcm tool. The DVF must represent
# deformations in x, y and z directions in the DICOM LPS coordinate system.
#
# APA, 4/3/2023

import os
from datetime import datetime
from random import randint

import numpy as np
import scipy.io as sio
import SimpleITK as sitk
from pydicom.dataset import Dataset, FileDataset
from pydicom.sequence import Sequence
from pydicom.uid import generate_uid

from cerr.dcm_export import iod_helper
from cerr.dataclasses import scan as scn

org_root = '1.3.6.1.4.1.9590.100.1.2.'


def getDcmTagVals(baseScanNum, planC, seriesOpts={}):

    sInfo = planC.scan[baseScanNum].scanInfo[0]

    pat_tags = {"PatientName": sInfo.patientName,
                "PatientID": sInfo.patientID,
                "PatientBirthDate": sInfo.patientBirthDate,
                "PatientSex": sInfo.patientSex,
                "PatientAge": "",
                "PatientSize": sInfo.patientSize,
                "PatientWeight": sInfo.patientWeight
                }

    study_tags = {"StudyDate": sInfo.studyDate,
                  "StudyTime": sInfo.studyTime,
                  "StudyDescription": sInfo.studyDescription,
                  "StudyInstanceUID": sInfo.studyInstanceUID,
                  "StudyID": ""
                  }

    dt = datetime.now()
    series_tags = {
        'Modality': 'REG',
        'SeriesDate': seriesOpts.get('SeriesDate', dt.strftime("%Y%m%d")),
        'SeriesTime': seriesOpts.get('SeriesTime', dt.strftime("%H%M%S.%f")),
        'SeriesDescription': seriesOpts.get('seriesDescription', "Generated by pyCERR"),
        'SeriesInstanceUID': generate_uid(prefix=org_root),
        'SeriesNumber': str(randint(9010, 9900))
    }

    content_tags = {"ContentDescription": seriesOpts.get('ContentDescription', "DEFORMABLE REGISTRATION"),
                    "ContentLabel": seriesOpts.get('ContentLabel', "REGISTRATION")}

    return pat_tags, study_tags, series_tags, content_tags


def getRefImgSeq(scanNum, planC):
    """Referenced Image Sequence for all instances of a scan in planC."""
    refd_img_seq = Sequence()
    for sInfo in planC.scan[scanNum].scanInfo:
        ref_img_ds = Dataset()
        ref_img_ds.ReferencedSOPClassUID = sInfo.sopClassUID
        ref_img_ds.ReferencedSOPInstanceUID = sInfo.sopInstanceUID
        refd_img_seq.append(ref_img_ds)
    return refd_img_seq


def addRefSeriesSequence(ds: FileDataset, baseScanNum, movScanNum, planC):
    """Reference the base (fixed) and moving image series.

    Series belonging to the same study as the REG object go into
    ReferencedSeriesSequence; series from other studies go into
    StudiesContainingOtherReferencedInstancesSequence.
    """
    regStudyUID = planC.scan[baseScanNum].scanInfo[0].studyInstanceUID

    ref_series_seq = Sequence()
    other_studies_seq = Sequence()
    for scanNum in [baseScanNum, movScanNum]:
        sInfo = planC.scan[scanNum].scanInfo[0]
        ref_series_ds = Dataset()
        ref_series_ds.ReferencedInstanceSequence = getRefImgSeq(scanNum, planC)
        ref_series_ds.SeriesInstanceUID = sInfo.seriesInstanceUID
        if sInfo.studyInstanceUID == regStudyUID:
            ref_series_seq.append(ref_series_ds)
        else:
            study_ds = Dataset()
            study_ds.StudyInstanceUID = sInfo.studyInstanceUID
            study_ds.ReferencedSeriesSequence = Sequence([ref_series_ds])
            other_studies_seq.append(study_ds)

    ds.ReferencedSeriesSequence = ref_series_seq
    if len(other_studies_seq) > 0:
        ds.StudiesContainingOtherReferencedInstancesSequence = other_studies_seq
    return ds


def getDVFMetadata(dvfFile):
    """Read a DVF image file (nii/mha/mhd) and return the grid re-oriented to LPS."""
    reader = sitk.ImageFileReader()
    reader.SetFileName(dvfFile)
    reader.LoadPrivateTagsOn()
    reader.ReadImageInformation()
    image = reader.Execute()
    img_ori = image.GetDirection()
    original_orient_str = sitk.DICOMOrientImageFilter_GetOrientationFromDirectionCosines(img_ori)
    image = sitk.DICOMOrient(image, "LPS")
    dvf_matrix = sitk.GetArrayFromImage(image)
    origin = list(image.GetOrigin())
    orient = list(image.GetDirection())[:6]
    dim = list(image.GetSize())
    res = list(image.GetSpacing())
    return dvf_matrix, origin, orient, dim, res, original_orient_str


def createDeformSeq(baseScanNum, movScanNum, dvfFile, planC,
                    preDefMatrix=None, postDefMatrix=None):
    """Build the Deformable Registration Sequence (0064,0002).

    Item 1 references the base (fixed) scan with an identity registration.
    Item 2 references the moving scan and carries the DVF grid along with
    optional pre/post rigid transformation matrices.
    """
    def_seq = Sequence()

    base_ds = Dataset()
    base_ds.SourceFrameOfReferenceUID = planC.scan[baseScanNum].scanInfo[0].frameOfReferenceUID
    base_ds.RegistrationTypeCodeSequence = getREGTypeCodeSeq('base')
    base_ds.ReferencedImageSequence = getRefImgSeq(baseScanNum, planC)
    def_seq.append(base_ds)

    mov_ds = Dataset()
    mov_ds.SourceFrameOfReferenceUID = planC.scan[movScanNum].scanInfo[0].frameOfReferenceUID
    mov_ds.DeformableRegistrationGridSequence = getDVFGridSeq(dvfFile)
    mov_ds.PreDeformationMatrixRegistrationSequence = getMatrixSeq(preDefMatrix)
    mov_ds.PostDeformationMatrixRegistrationSequence = getMatrixSeq(postDefMatrix)
    mov_ds.RegistrationTypeCodeSequence = getREGTypeCodeSeq('mov')
    mov_ds.ReferencedImageSequence = getRefImgSeq(movScanNum, planC)
    def_seq.append(mov_ds)

    return def_seq


def getREGTypeCodeSeq(series_type):
    reg_type_seq = Sequence()
    reg_type_ds = Dataset()
    if series_type == "base":
        reg_type_ds.CodingSchemeDesignator = "DCM"
        reg_type_ds.CodeValue = "125021"
        reg_type_ds.CodeMeaning = "Frame of Reference Identity"
    elif series_type == "mov":
        reg_type_ds.CodingSchemeDesignator = "DCM"
        reg_type_ds.CodeValue = "125024"
        reg_type_ds.CodeMeaning = "Image Content-based Alignment"
    reg_type_seq.append(reg_type_ds)
    return reg_type_seq


def getDVFGridSeq(dvfFile):
    dvf_grid_seq = Sequence()
    grid_ds = Dataset()
    dvf_matrix, origin, orient, dim, res, original_orient_str = getDVFMetadata(dvfFile)
    grid_ds.ImagePositionPatient = list(origin)
    grid_ds.ImageOrientationPatient = orient
    grid_ds.GridDimensions = dim
    grid_ds.GridResolution = res
    # sitk array is (z, y, x, component); VectorGridData is x1,y1,z1,x2,...
    # iterating fastest along x (columns), then rows, then slices
    dx = dvf_matrix[:, :, :, 0].ravel(order="C")
    dy = dvf_matrix[:, :, :, 1].ravel(order="C")
    dz = dvf_matrix[:, :, :, 2].ravel(order="C")
    vector_grid_matrix = np.array([dx, dy, dz], dtype=np.single).transpose()
    grid_ds.VectorGridData = vector_grid_matrix.tobytes()
    dvf_grid_seq.append(grid_ds)
    return dvf_grid_seq


def getMatrixSeq(deformMatrix=None):
    """Rigid transformation matrix sequence.

    Args:
        deformMatrix: Optional. A 4x4 numpy array, or the path to an ITK
            .mat file containing an affine transform. Defaults to identity.
    """
    dvf_matrix_seq = Sequence()
    dvf_matrix_ds = Dataset()
    if isinstance(deformMatrix, np.ndarray):
        transform_matrix = [float(v) for v in np.asarray(deformMatrix).flatten()]
    else:
        transform_matrix = loadMatrixFile(deformMatrix)
    dvf_matrix_ds.FrameOfReferenceTransformationMatrixType = "RIGID"
    dvf_matrix_ds.FrameOfReferenceTransformationMatrix = transform_matrix
    dvf_matrix_seq.append(dvf_matrix_ds)
    return dvf_matrix_seq


def loadMatrixFile(deform_matrix_file):
    """Load a 4x4 transformation matrix from an ITK-compatible .mat file.

    Returns the identity matrix when no file is supplied.
    """
    if deform_matrix_file is not None and os.path.exists(deform_matrix_file):
        tf_contents = sio.loadmat(deform_matrix_file)
        affine_3x3 = tf_contents["AffineTransform_double_3_3"]
        center = tf_contents["fixed"]
        matrix = np.reshape(affine_3x3[:9], (3, 3))
        translation = affine_3x3[9:12]
        last_row = np.expand_dims(np.array([0, 0, 0, 1]), axis=1).T
        offset = translation + center - np.dot(matrix, center)
        matrix = np.concatenate((matrix, offset), axis=1)
        matrix = np.concatenate((matrix, last_row), axis=0)
        transform_matrix = [float(v) for v in matrix.flatten()]
    else:
        transform_matrix = [float(v) for v in np.eye(4).flatten()]

    return transform_matrix


def createFromDVFFile(baseScanNum, movScanNum, dvfFile, filePath, planC,
                      preDefMatrix=None, postDefMatrix=None, seriesOpts={}):
    """Export a DVF file to a Deformable Spatial Registration (REG) DICOM file.

    Args:
        baseScanNum (int): Index of the base (fixed) scan in planC.scan.
        movScanNum (int): Index of the moving scan in planC.scan.
        dvfFile (str): Path to an ITK-readable file (nii, nii.gz, mha, mhd)
            containing the deformation vector field. The DVF must have three
            components representing deformations in x, y and z directions in
            the DICOM LPS coordinate system (mm).
        filePath (str): Output DICOM file path.
        planC (cerr.plan_container.PlanC): pyCERR's plan container object.
        preDefMatrix: Optional pre-deformation rigid transform - a 4x4 numpy
            array or path to an ITK .mat file. Defaults to identity.
        postDefMatrix: Optional post-deformation rigid transform - a 4x4 numpy
            array or path to an ITK .mat file. Defaults to identity.
        seriesOpts (dict): Optional 'seriesDescription', 'SeriesDate',
            'SeriesTime', 'ContentDescription', 'ContentLabel'.
    """

    pat_tags, study_tags, series_tags, content_tags = \
        getDcmTagVals(baseScanNum, planC, seriesOpts)

    file_meta = iod_helper.getFileMeta('REG')
    ds = FileDataset(filePath, {}, file_meta=file_meta, preamble=b"\0" * 128)

    ds = iod_helper.addSOPCommonTags(ds)
    ds = iod_helper.addPatientTags(ds, pat_tags)
    ds = iod_helper.addStudyTags(ds, study_tags)
    ds = iod_helper.addSeriesTags(ds, series_tags)
    ds = iod_helper.addEquipmentTags(ds, {})
    ds = iod_helper.addContentTags(ds, content_tags)

    ds.FrameOfReferenceUID = planC.scan[baseScanNum].scanInfo[0].frameOfReferenceUID
    ds = addRefSeriesSequence(ds, baseScanNum, movScanNum, planC)
    ds.DeformableRegistrationSequence = createDeformSeq(
        baseScanNum, movScanNum, dvfFile, planC, preDefMatrix, postDefMatrix)

    print("Writing REG file ...", filePath)
    ds.save_as(filePath)
    print("File saved.")


def create(deformNum, filePath, planC, movScanNum=None,
           preDefMatrix=None, postDefMatrix=None, seriesOpts={}):
    """Export a pyCERR deform object to a Deformable Spatial Registration (REG) DICOM file.

    Args:
        deformNum (int): Index of deformation in planC.deform. The deform
            object must reference a vector field file
            (deformOutFileType == 'vf').
        filePath (str): Output DICOM file path.
        planC (cerr.plan_container.PlanC): pyCERR's plan container object.
        movScanNum (int): Optional. Index of the moving scan in planC.scan.
            When None, it is resolved from the deform object's movScanUID.
        preDefMatrix: Optional pre-deformation rigid transform - a 4x4 numpy
            array or path to an ITK .mat file. Defaults to identity.
        postDefMatrix: Optional post-deformation rigid transform - a 4x4 numpy
            array or path to an ITK .mat file. Defaults to identity.
        seriesOpts (dict): Optional 'seriesDescription', 'SeriesDate',
            'SeriesTime', 'ContentDescription', 'ContentLabel'.
    """

    deformObj = planC.deform[deformNum]

    if deformObj.deformOutFileType != 'vf':
        raise ValueError("REG export requires a vector field deform object "
                         "(deformOutFileType == 'vf'). Use "
                         "cerr.registration.register.calcVectorField to "
                         "generate one from a transformation.")
    dvfFile = deformObj.deformOutFilePath
    if not dvfFile or not os.path.exists(dvfFile):
        raise FileNotFoundError("Vector field file not found: %s" % dvfFile)

    baseScanNum = scn.getScanNumFromUID(deformObj.baseScanUID, planC)
    if movScanNum is None:
        movScanNum = scn.getScanNumFromUID(deformObj.movScanUID, planC)
    if baseScanNum is None or movScanNum is None:
        raise ValueError("Could not resolve base/moving scan from the deform "
                         "object's scan UIDs. Pass movScanNum explicitly if "
                         "the moving scan resides in this planC.")

    createFromDVFFile(baseScanNum, movScanNum, dvfFile, filePath, planC,
                      preDefMatrix, postDefMatrix, seriesOpts)
