# Module to export dose distribution to RTDOSE DICOM
#
# APA, 7/3/2026

from datetime import datetime
import numpy as np
from pydicom.uid import generate_uid
from pydicom.dataset import Dataset, FileDataset
from pydicom.sequence import Sequence
from random import randint
from cerr.dcm_export import iod_helper
from cerr.dataclasses import scan as scn

org_root = '1.3.6.1.4.1.9590.100.1.2.'


def getDcmTagVals(doseNum, planC, seriesOpts={}):

    doseObj = planC.dose[doseNum]
    assocScanNum = scn.getScanNumFromUID(doseObj.assocScanUID, planC)
    sInfo = planC.scan[assocScanNum].scanInfo[0]

    pat_tags = {"PatientName": sInfo.patientName,
                "PatientID": sInfo.patientID,
                "PatientBirthDate": sInfo.patientBirthDate,
                "PatientSex": sInfo.patientSex,
                "PatientAge": "",
                "PatientSize": sInfo.patientSize,
                "PatientWeight": sInfo.patientWeight
                }

    study_tags = {"StudyDate": sInfo.studyDate,
                  "StudyTime": sInfo.studyTime,
                  "StudyDescription": sInfo.studyDescription,
                  "StudyInstanceUID": sInfo.studyInstanceUID,
                  "StudyID": ""
                  }

    dt = datetime.now()
    series_tags = {
        'Modality': 'RTDOSE',
        'SeriesDate': seriesOpts.get('SeriesDate', dt.strftime("%Y%m%d")),
        'SeriesTime': seriesOpts.get('SeriesTime', dt.strftime("%H%M%S.%f")),
        'SeriesDescription': seriesOpts.get('seriesDescription', doseObj.fractionGroupID or "Generated by pyCERR"),
        'SeriesInstanceUID': generate_uid(prefix=org_root),
        'SeriesNumber': str(randint(9010, 9900))
    }

    return pat_tags, study_tags, series_tags


def create(doseNum, filePath, planC, seriesOpts={}):
    """Export a pyCERR dose object to a multi-frame RTDOSE DICOM file.

    Args:
        doseNum (int): Index of dose in planC.dose.
        filePath (str): Output DICOM file path.
        planC (cerr.plan_container.PlanC): pyCERR's plan container object.
        seriesOpts (dict): Optional 'seriesDescription', 'SeriesDate', 'SeriesTime'.
    """

    doseObj = planC.dose[doseNum]
    pat_tags, study_tags, series_tags = getDcmTagVals(doseNum, planC, seriesOpts)

    file_meta = iod_helper.getFileMeta('RTDOSE')
    ds = FileDataset(filePath, {}, file_meta=file_meta, preamble=b"\0" * 128)

    ds = iod_helper.addSOPCommonTags(ds)
    ds = iod_helper.addPatientTags(ds, pat_tags)
    ds = iod_helper.addStudyTags(ds, study_tags)
    ds = iod_helper.addSeriesTags(ds, series_tags)
    ds = iod_helper.addEquipmentTags(ds, {})

    # Frames in original DICOM slice order (doseArray was flipped at import
    # when the DICOM slice direction did not match pyCERR's)
    doseFrames = np.transpose(doseObj.doseArray, (2, 0, 1))  # (slice, row, col)
    if not doseObj.cerrDcmSliceDirMatch:
        doseFrames = np.flip(doseFrames, axis=0)
    numFrames = doseFrames.shape[0]

    # Geometry from Image2PhysicalTransM, the (col,row,slc)->DICOM (cm) affine
    # used at import; convert cm to mm
    transM = np.asarray(doseObj.Image2PhysicalTransM)
    ipp = np.matmul(transM, [0, 0, 0, 1])[:3] * 10
    imgOri = np.asarray(doseObj.imageOrientationPatient, dtype=float).flatten()
    normal = np.cross(imgOri[:3], imgOri[3:])
    frameIdxM = np.vstack((np.zeros((2, numFrames)), np.arange(numFrames), np.ones(numFrames)))
    framePosM = np.matmul(transM, frameIdxM)[:3, :] * 10
    gridFrameOffsets = np.matmul(normal, framePosM - framePosM[:, [0]])  # signed, mm

    ds.FrameOfReferenceUID = doseObj.frameOfReferenceUID
    ds.ImagePositionPatient = [float(v) for v in ipp]
    ds.ImageOrientationPatient = [float(v) for v in imgOri]
    colSpacing = float(np.linalg.norm(transM[:3, 0])) * 10
    rowSpacing = float(np.linalg.norm(transM[:3, 1])) * 10
    ds.PixelSpacing = [rowSpacing, colSpacing]
    ds.NumberOfFrames = numFrames
    ds.FrameIncrementPointer = (0x3004, 0x000C)  # GridFrameOffsetVector
    ds.GridFrameOffsetVector = [float(v) for v in gridFrameOffsets]

    # Dose module
    ds.DoseUnits = doseObj.doseUnits.upper() if doseObj.doseUnits else "GY"
    ds.DoseType = doseObj.doseType.upper() if doseObj.doseType else "PHYSICAL"
    ds.DoseSummationType = doseObj.doseSummationType if doseObj.doseSummationType else "PLAN"
    ds.DoseComment = doseObj.doseDescription

    # Scale dose to unsigned 32-bit integers
    maxDose = float(doseFrames.max())
    doseGridScaling = maxDose / (2**32 - 1) if maxDose > 0 else 1.0
    ds.DoseGridScaling = doseGridScaling
    pixelArray = np.round(doseFrames / doseGridScaling).astype(np.uint32)

    ds.SamplesPerPixel = 1
    ds.PhotometricInterpretation = "MONOCHROME2"
    ds.Rows = pixelArray.shape[1]
    ds.Columns = pixelArray.shape[2]
    ds.BitsAllocated = 32
    ds.BitsStored = 32
    ds.HighBit = 31
    ds.PixelRepresentation = 0
    ds.PixelData = pixelArray.tobytes()

    # Reference to RTPLAN if available
    if doseObj.refRTPlanSopInstanceUID:
        refPlan = Dataset()
        refPlan.ReferencedSOPClassUID = "1.2.840.10008.5.1.4.1.1.481.5"
        refPlan.ReferencedSOPInstanceUID = doseObj.refRTPlanSopInstanceUID
        ds.ReferencedRTPlanSequence = Sequence([refPlan])

    print("Writing RTDOSE file ...", filePath)
    ds.save_as(filePath)
    print("File saved.")
